target("libcode")
    set_kind("static")
    add_files("src/lib/*.cpp")
    set_languages("cxx20")

target("bincode_artifact")
    set_kind("binary")
    add_files("src/bin/artifact/*.cpp")
    add_deps("libcode")
    set_languages("cxx20")

target("tests")
    set_kind("binary")
    add_files("src/bin/tests.cpp")
    add_deps("libcode")
    set_languages("cxx20")
